COPY works now without OF (in most cases)
JannikArndt/Canal pull request #27
Opened 2016-10-27 09:23 UTC by koljag

Including copybooks needed the Cobol source "COPY Name OF Folder", now "COPY Name" also works as long as the file Name is the only file with that name in the workspace or at least the only file named Name.cbl.

2016-10-31 09:20 UTC, koljag commented
I hope the multiple query evaluation is now fixed with these changes. The no file found case was not handled before so I thought it would be okay like that, but I added a related Exception which is handled and communicated to the user now.

2016-11-01 14:08 UTC, JannikArndt requested changes

2016-11-01 14:08 UTC, JannikArndt commented on Model/Exceptions/CopiedRessourceNotFoundException.cs
> +        public CopiedRessourceNotFoundException(string filename) : base("The file " + filename + " has no occurs in the file cache and could therefore not be linked!")
`"The file " + filename + " could not be found.`

2016-11-01 14:08 UTC, JannikArndt commented on Model/Exceptions/CopiedRessourceNotFoundException.cs
> +    public class CopiedRessourceNotFoundException : Exception
Shloud derive from CanalException

2016-11-01 14:08 UTC, JannikArndt commented on Model/Exceptions/CopiedRessourceNotIdentifiedDistinctlyByNameException.cs
> +    public class CopiedRessourceNotIdentifiedDistinctlyByNameException : Exception
Should derive from `CanalException`

2016-11-01 14:08 UTC, JannikArndt commented on Util/FileUtil.cs
> +            if (!allFileReferencesWithGivenName.Any())
You can use `.None()` (Extension specific to Canal project ;) )

2016-11-01 14:08 UTC, JannikArndt commented on Util/FileUtil.cs
> +                    _files.AsParallel()
Since ideally this list has just one entry, `.AsParallel()` is a bit too much overhead

2016-11-01 15:20 UTC, JannikArndt approved these changes

2016-11-01 15:21 UTC, merged